### Variables

@baseUrl = https://bookmarkhive.test
@contentType = application/json
@mergePatchContentType = application/json


### List own bookmarks

GET {{baseUrl}}/api/users/me/bookmarks
Authorization: Bearer {{jwt}}


### List own bookmarks with tag filter (AND logic)

GET {{baseUrl}}/api/users/me/bookmarks?tags=tag-one,tag-two
Authorization: Bearer {{jwt}}


### List own bookmarks with single tag filter

GET {{baseUrl}}/api/users/me/bookmarks?tags=inbox-tray-inbox
Authorization: Bearer {{jwt}}


### Create bookmark

POST {{baseUrl}}/api/users/me/bookmarks
Content-Type: {{contentType}}
Authorization: Bearer {{jwt}}

{
  "title": "Test Bookmark",
  "url": "https://example.com",
  "tags": [
    "/api/users/me/tags/test-tag",
    "/api/users/me/tags/guitar"
  ]
}


### Create bookmark with tags

POST {{baseUrl}}/api/users/me/bookmarks
Content-Type: {{contentType}}
Authorization: Bearer {{jwt}}

{
  "title": "Test Bookmark",
  "url": "https://example.com",
  "tags": [
    {
      "name": "Test Should Fail"
    }
  ]
}


### Create bookmark with archive file

# First upload a file to get the file object IRI, then use it here
POST {{baseUrl}}/api/users/me/bookmarks
Content-Type: {{contentType}}
Authorization: Bearer {{jwt}}

{
  "title": "Test Bookmark with Archive",
  "url": "https://example.com",
  "archive": "/api/users/me/files/019b2192-037a-717a-b93c-423807f701c1"
}


### Create bookmark with main image file

# First upload a file to get the file object IRI, then use it here
POST {{baseUrl}}/api/users/me/bookmarks
Content-Type: {{contentType}}
Authorization: Bearer {{jwt}}

{
  "title": "Test Bookmark with Main Image",
  "url": "https://example.com",
  "mainImage": "/api/users/me/files/{fileObjectId}"
}


### Get own bookmark

GET {{baseUrl}}/api/users/me/bookmarks/{bookmarkId}
Authorization: Bearer {{jwt}}


### Edit own bookmark

PATCH {{baseUrl}}/api/users/me/bookmarks/{bookmarkId}
Content-Type: {{mergePatchContentType}}
Authorization: Bearer {{jwt}}

{
  "title": "Updated Title",
  "url": "https://updated.com",
  "tags": [
    "/api/users/me/tags/tag-2",
    "/api/users/me/tags/tag-3"
  ]
}


### Delete own bookmark

DELETE {{baseUrl}}/api/users/me/bookmarks/{bookmarkId}
Authorization: Bearer {{jwt}}


### List public bookmarks of a user

GET {{baseUrl}}/api/profile/{username}/bookmarks


### List public bookmarks of a user with tag filter

GET {{baseUrl}}/api/profile/{username}/bookmarks?tags=tag-one,tag-two


### Get public bookmark

GET {{baseUrl}}/api/profile/{username}/bookmarks/{bookmarkId}}


### Cursor-based pagination - First page

GET {{baseUrl}}/api/users/me/bookmarks
Authorization: Bearer {{jwt}}


### Cursor-based pagination - Next page (use last bookmark ID from previous response)

GET {{baseUrl}}/api/users/me/bookmarks?after={lastBookmarkId}
Authorization: Bearer {{jwt}}


###
